name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: set up git repository
        uses: actions/checkout@v2

      # for .nojekyll see https://stackoverflow.com/a/64544659
      # remove .htmlcov/.gitignore otherwise not pushed to gh-pages branch
      - name: generate sphinx docs
        run: |
          git describe --always
          make install-local
          git describe --always
          . .venv/bin/activate && make docs
          git describe --always
          touch docs/sphinx/build/html/.nojekyll
          rm docs/sphinx/build/html/.htmlcov/.gitignore

      - name: deploy pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: docs/sphinx/build/html
